{{- $lection := .Values.lectionName }}
{{- $namespace := .Values.classroom }}
{{- $port := .Values.port }}
{{- range $i, $e := until (int .Values.replicaCount) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ $lection }}-vnc-{{ $i }}
  name: {{ $lection }}-vnc-svc-{{ $i }}
  namespace: "{{ $namespace }}"
spec:
  ports:
  - port: {{ $port }}
    protocol: TCP
    targetPort: {{ $port }}
  selector:
    run: {{ $lection }}-vnc-{{ $i }}
  sessionAffinity: None
  type: NodePort
---
{{- end }}
