{{- range .Values.classrooms }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: "{{ . }}"
  name: deny-all-{{ . }}
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
{{- end }}
